// Generated by Concile. Do not edit.
export { query, mutation, action, httpAction, httpRouter } from "@concile/executor";
export type { DataModel, TableNames, Doc, Id } from "./dataModel";
export type { Api, FunctionReference } from "./api";
export type { Internal } from "./internal";
export { cronJobs } from "@concile/scheduler";
import { anyApi } from "@concile/client";
import type { Api } from "./api";
import type { Internal } from "./internal";
export const api = anyApi as Api;
export const internal = anyApi as Internal;

// Component context contributions (ctx.<component>), typed.
declare module "@concile/executor" {
  interface QueryCtx {
    auth: import("@concile/auth").AuthContext;
    scheduler: import("@concile/scheduler").SchedulerContext;
    workflow: import("@concile/workflow").WorkflowContext;
  }
  interface MutationCtx {
    auth: import("@concile/auth").AuthContext;
    scheduler: import("@concile/scheduler").SchedulerContext;
    workflow: import("@concile/workflow").WorkflowContext;
  }
}
